services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python start.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: OTP_EXPIRY_SECONDS
        value: "300"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: RENDER
        value: "true"